title: My First Page!
author: Luiz Fernando de Oliveira Rodrigues
email: luizfernando.rodrigues@gmail.com
description: This is my first page. I will change so far as will learn new stuffs...
# social links
twitter_username: lfernando_zero
github_username: luizfrodrigues
theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
